package org.actionLog;

/**
 * Application log.
 *
 * It could be used for aggregating events generated by application independent of storage used.
 */
public interface ActionLog {
    /**
     * Adds new entry into log
     * @param entry log entry
     */
    void append(LogEntry entry);

    /**
     * Retrieves actual capacity based on log events
     * @param name container name
     * @return actual capacity of container
     */
    double findActualCapacity(String name);
}
