package org.actionLog;

import java.util.*;

/**
 * Application log.
 *
 * It could be used for aggregating events generated by application independent of storage used.
 */
public interface ApplicationLog {
    /**
     * Adds new entry into log
     * @param entry log entry
     */
    void append(LogEntry entry);

    /**
     * Retrieves names of containers that have the biggest amount of errors.
     * @return set of container's names
     */
    Set<String> getContainerNameWithTheMostErrors();

    /**
     * Retrieves names of containers that have the biggest amount of operations.
     * @param operationType operation type
     * @return set of container's names
     */
    Set<String> getContainerWithMaxOpType(String operationType);

    /**
     * Retrieves actual capacity based on log events
     * @param name container name
     * @return actual capacity of container
     */
    double findActualCapacity(String name);
}
